### ISSUE TITLE
newb question

### ISSUE THREAD

**Issue by xpufx** [al-jshen/dashboard#2]
Hi. I came across this repo looking for a sample app to start with. I don't see how it works but I think this app works both on the browser and as an electron app. How does that work? Can you direct me to some docs?

**Comment by al-jshen** [comment]
It's been a while since I've touched this but no, I don't believe that this works in the browser. It has some Electron-specific code. If you want to run the Electron app you start the app with `npm run start` and then start Electron with `electron .` inside the repo directory. Things might be out of date though.

**Comment by xpufx** [comment]
Thank you!
